songs = ["justin bieber - yummy",
"leviathanjptv - chug jug with you (number one victory royale)",
"oliver tree - life goes on",
"lil uzi vert - cs",
"hot chelle rae - tonight tonight",
"lukas graham - 7 years",
"yung gravy - 1 thot 2 thot red thot blue thot",
"john mayer - your body is a wonderland",
"fall out boy - centuries",
"swae lee - krabby step (with tyga & lil mosey)",
"dax - propaganda",
"steve aoki - pretender",
"100 gecs - money machine",
"eminem - fack",
"william shatner - ponder the mystery - revisited version",
"joe pesci - wise guy",
"stitches - molly cyrus",
"smash mouth - all star",
"bo burnham - bezos i",
"rednex - cotton eye joe",
"jpro - jump",
"avril lavigne - hello kitty",
"penelope scott - rt",
"falling in reverse - game over",
"van morrison - no more lockdown",
"queen - we will rock you",
"dababy - no condom",
"ilovefriday - mia khalifa",
"midnight oil - beds are burning - remastered",
"imagine dragons - thunder",
"cher lloyd - swagger jagger",
"ylvis - the fox (what does the fox say?)",
"tambo - toxic gossip train (miranda sings apology)",
"sam hunt - body like a back road",
"645ar - 4 da trap",
"jim jones - pop champagne (feat. juelz santana) - explicit album version",
"jason derulo - trumpets",
"tramp stamps - i\'d rather die",
"marshmello - happier",
"arizona zervas - roxanne",
"kanye west - lift yourself",
"taylor swift - me! (feat. brendon urie of panic! at the disco)",
"rachel platten - fight song",
"the j. geils band - centerfold",
"melanie martinez - wheels on the bus",
"ajr - netflix trip",
"train - hey, soul sister",
"aqua - barbie girl",
"bobby mcferrin - don\'t worry be happy",
"kid rock - never enough",
"alison gold - shush up",
"black eyed peas - double d\'z",
"walker hayes - fancy like",
"falling in reverse - bad girls club",
"logic - everyday",
"david guetta - i\'m good (blue)",
"crazy town - butterfly",
"imagine dragons - radioactive",
"addison rae - obsessed",
"maroon 5 - moves like jagger",
"lil wayne - prom queen",
"hobo johnson - peach scone",
"corpse - e-girls are ruining my life!",
"ajr - thirsty",
"lil xan - diamonds",
"theory of a deadman - hate my life",
"mgk - emo girl (feat. willow)",
"justin bieber - drummer boy",
"kid cudi - judgmental c**t",
"gayle - abcdefu",
"lil dicky - earth",
"awolnation - sail",
"tom jones - what\'s new pussycat?",
"paul mccartney - temporary secretary - remastered 2011",
"dream - mask",
"the chainsmokers - #selfie",
"earl sweatshirt - east",
"billy ray cyrus - achy breaky heart",
"brokencyde - freaxxx",
"ybn nahmir - soul train",
"3oh!3 - my first kiss (feat. ke$ha)",
"sam smith - unholy (feat. kim petras)",
"aqua - barbie girl",
"tom macdonald - whiteboy",
"rebecca black - friday",
"luke bryan - country girl (shake it for me)",
"corey feldman - angelic 2 the core",
"ed sheeran - galway girl",
"nickelback - she keeps me up",
"lil pump - pump rock x heavy metal",
"hopsin - happy ending",
"chance the rapper - hot shower",
"buckcherry - crazy bitch",
"quavo - go all the way",
"kid rock - don\'t tell me how to live",
"leah kate - twinkle twinkle",
"masked wolf - astronaut in the ocean",
"dababy - red light green light",
"tones and i - dance monkey",
"vanilla ice - ice ice baby",
"taylor swift - shake it off",
"3oh!3 - donttrustme",
"brad paisley - accidental racist (feat. ll cool j)",
"kanye west - drunk and hot girls",
"dax - joker",
"panic! at the disco - high hopes",
"eminem - tone deaf",
"lil pump - mona lisa",
"huddy - all the things i hate about you",
"gawne - death to mumble rap",
"icejjfish - on the floor",
"jake paul - it\'s everyday bro",
"soulja boy - rick & morty",
"american authors - best day of my life",
"james blunt - you\'re beautiful",
"katy perry - swish swish",
"nle choppa - slut me out",
"natasha bedingfield - pocketful of sunshine",
"david bowie - the laughing gnome",
"azzyland - money",
"macklemore & ryan lewis - downtown (feat. melle mel, grandmaster caz, kool moe dee & eric nally)",
"lanze - the grinch",
"tisto - jackie chan",
"xxxtentacion - school shooters (feat. lil wayne)",
"rod stewart - kookooaramabama",
"drake bell - gucci gang",
"flo rida - my house",
"justin timberlake - supplies",
"kiss - rock and roll all nite",
"panic! at the disco - star spangled banger",
"bastille - pompeii",
"pinkfong - baby shark",
"dj khaled - i\'m the one (feat. justin bieber, quavo, chance the rapper & lil wayne)",
"x ambassadors - jungle",
"steven seagal - strut",
"we three - hell as well",
"five for fighting - superman (it\'s not easy)",
"usher - omg (feat. will.i.am)",
"6ix9ine - fefe (feat. nicki minaj & murda beatz)",
"saliva - click click boom",
"flyysoulja - im an island boy",
"jumex - loner",
"cara paige - toyota tacoma",
"brain - cocaine (feat. lil dicky)",
"rebecca zamolo - among us in real life",
"nickelback - rockstar",
"the beatles - yellow submarine",
"gwen stefani - wind it up",
"93punx - 3 years sober",
"maroon 5 - animals",
"imagine dragons - bones",
"eddie murphy - boogie in your butt",
"brandyn h*wood bordeaux - could it be you (punk rock chick)",
"creed - with arms wide open",
"jason aldean - try that in a small town",
"sia - hey boy (feat. burna boy)",
"will.i.am - t.h.e (the hardest ever)",
"mori calliope - huge w",
"twenty one pilots - lane boy",
"dawin - dessert - remix",
"florida georgia line - cruise",
"frank sinatra - baby, it\'s cold outside (with dorothy kirsten)",
"theory of a deadman - bitch came back",
"nicholas fraser - why you always lying?",
"one gotti - wah gwan delilah",
"counting crows - big yellow taxi",
"psy - gangnam style ()",
"antonio vivaldi - concerto no. 1 in e major, op. 8, rv 269, \"la primavera\" (spring): i. allegro",
"raelynn - god made girls",
"yung gravy - mr. clean",
"daniel powter - bad day",
"waka flocka flame - fist pump (feat. b.o.b)",
"vanessa hudgens - sneakernight - single version",
"artists for haiti - we are the world 25 for haiti",
"t-spoon - sex on the beach - original mix",
"fifth harmony - work from home (feat. ty dolla $ign)",
"len - steal my sunshine",
"mario judah - afraid of love",
"dominic fike - cancel me",
"cash cobain - grippy",
"guns n\' roses - my world",
"miley cyrus - cattitude (feat. rupaul)",
"nas - big girl",
"robin thicke - blurred lines",
"sisqo - thong song",
"black eyed peas - ritmo (bad boys for life)",
"insane clown posse - miracles",
"twenty one pilots - house of gold",
"post malone - insane",
"rick astley - never gonna give you up",
"ajj - ladykiller",
"bad meets evil - lighters",
"justin timberlake - can\'t stop the feeling! (from dreamworks animation\'s \"trolls\")",
"crazy frog - axel f",
"jojo siwa - karma",
"wallpaper. - fucking best song everrr",
"katy perry - woman\'s world",
"theory of a deadman - bad girlfriend",
"future - plutoski",
"a.j. & big justice - we bring the boom!",
"imagine dragons - take me to the beach",
"black eyed peas - my humps",
"paul mccartney - fuh you",
"nicki minaj - big foot",
"ringo starr - you\'re sixteen (you\'re beautiful and you\'re mine)",
"flo rida - still missin",
"tom macdonald - facts",
"bella poarch - build a bitch",
"andy grammer - honey, i\'m good",
"luis fonsi - despacito",
"jennifer murphy go girl - i want to be neenja",
"macklemore & ryan lewis - thrift shop (feat. wanz)",
"usher - a-town girl",
"adonis - my man freestyle",
"$ - 530",
"bebe rexha - meant to be (feat. florida georgia line)",
"1 fish man - one pound fish",
"lil mabu - oppy day",
"rl grime - ucla",
"mr plenty - suicide",
"tones and i - ur so f**king cool",
"megan thee stallion - mamushi (feat. yuki chiba)",
"charlie puth - marvin gaye (feat. meghan trainor)",
"say anything - i, vibrator",
"snake eyes"];

let choice;
let deleted = [];

function init() {
        deleted = JSON.parse(localStorage.getItem('deletedSongs'));
        songs = songs.filter(a => !deleted.includes(a));
}

// on load: load localstorage into deleted array
// on load: filter songs array using !deleted.includes
function loadSongs() {

}

// on click: visual stuff. plays audio & delays the choice-making function
function icon() {
        new Audio("donk/dis-one.wav").play();
        setTimeout(delay,1220);
}

function delay() {
        // pick a song and set html to it. then update deleted array with the song
        choice = songs[Math.floor(Math.random()*songs.length)];
        document.getElementById("song").innerHTML = choice;
        deleted.push(choice);

        // on choice: save deleted array to localstorage
        localStorage.setItem('deletedSongs',JSON.stringify(deleted));

        // on choice: filter songs array using !deleted.includes
        songs = songs.filter(a => !deleted.includes(a));
        console.log(`length is ${songs.length}`);
}

init();